/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;
import com.mysql.cj.protocol.Resultset;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.io.IOException;
import static java.lang.Class.forName;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

 public class barang2 extends javax.swing.JFrame {
    public static Date gettgl(JTable table, int kolom){
        //Method untuk mmenampilkan tanggal dari JDateChooser 
        JTable tabel = table;
        String tgl = String.valueOf(tabel.getValueAt(tabel.getSelectedRow(), kolom));
        Date tanggal = null;
        try{
            tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(tgl);
            
        }catch(ParseException ex){
            Logger.getLogger(barang2.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        return tanggal;
    }
    public void otomatis(){
        //Method menampilkan id_supplier secara otomatis dari tabel ID_Barang
        try {
            Connection c = (Connection)Koneksi.configDB();
            Statement stm = c.createStatement();
            String sql = "SELECT * FROM barang ORDER BY ID_Barang DESC";
            ResultSet r = stm.executeQuery(sql);
            if (r.next()) {
                String id = r.getString("ID_Barang").substring(3);
                String TR = "" +(Integer.parseInt(id)+1);
                String nol = "";

                if (TR.length()==1)
                {nol = "000";}
                else if (TR.length()==2)
                {nol = "00";}
                else if (TR.length()==3) 
                {nol = "0";}
                else if (TR.length()==4) 
                {nol = "";}
                idbrgtxt1.setText("BRG" + nol + TR);
            } else {
                idbrgtxt1.setText("BRG0011");
            }
            r.close();
        
        } catch (Exception e) {
            e.printStackTrace();
        }
   
   }
       
     public void kosong_txt() {
         //method untuk  mengosongkan text dari kolom carisuppliertxt menjadi tidak bernilai (NULL) 
         caribrgtxt.setText(null);
     }

     public void Kosongkan_form() {
         //method untuk  mengosongkan text dari kolom yang telah didefinisikan menjadi tidak bernilai (NULL) 
         idbrgtxt1.setText(null);
         namatxt.setText(null);
         hargajualtxt.setText(null);
         stoktxt.setText(null);
         tanggalan.setDate(null);
         hbtxt.setText(null);
     }
public void tampilkan_data(){
     //Method yang berfungsi untuk menampilkan data dari tabel barang
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("No.");
        model.addColumn("id_Barang");
        model.addColumn("Nama_barang");
        model.addColumn("Harga_jual");
        model.addColumn("Harga_Beli");
        model.addColumn("Stok_barang");
        model.addColumn("Expired");
        String cari = caribrgtxt1.getText(); //pencarian data berdasarkan nama barang
        try {
            int no = 1;
            String sql = "Select * From barang WHERE Nama_barang LIKE'%" + cari + "%'";
            Connection con = (Connection) Koneksi.configDB();
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{no++, res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6)});

                tabel_barang.setModel(model); 
            }
        } catch (SQLException e) {
            System.out.println("ERROR :" + e.getMessage());

        }
    }
   
    public barang2() throws SQLException {
        //Method yang berfungsi untuk menampikan method-method yang telah didefinisikan 
        initComponents();
        tampilkan_data();
        Kosongkan_form();
        otomatis();  
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        findbutton = new javax.swing.JButton();
        caribrgtxt = new javax.swing.JTextField();
        findbutton2 = new javax.swing.JButton();
        caribrgtxt1 = new javax.swing.JTextField();
        roundedPanel17 = new org.hq.RoundedPanel();
        jLabel21 = new javax.swing.JLabel();
        roundedPanel16 = new org.hq.RoundedPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namatxt = new javax.swing.JTextField();
        hargajualtxt = new javax.swing.JTextField();
        stoktxt = new javax.swing.JTextField();
        deletebutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        refreshbtn = new javax.swing.JButton();
        idbrgtxt1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hbtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tanggalan = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        jPanel33 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        roundedPanel13 = new org.hq.RoundedPanel();
        labelexit = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panellogout = new org.hq.RoundedPanel();
        paneldash = new org.hq.RoundedPanel();
        labeltrans6 = new javax.swing.JLabel();
        panellap = new org.hq.RoundedPanel();
        labeltrans2 = new javax.swing.JLabel();
        panelkrwn = new org.hq.RoundedPanel();
        labeltrans3 = new javax.swing.JLabel();
        panelsup = new org.hq.RoundedPanel();
        labeltrans5 = new javax.swing.JLabel();
        panelrang = new org.hq.RoundedPanel();
        labeltrans4 = new javax.swing.JLabel();
        paneltrans = new org.hq.RoundedPanel();
        labeltrans1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(949, 748));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        findbutton.setBackground(new java.awt.Color(230, 230, 230));
        findbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/search_icon-icons.com_74128-picsay.png"))); // NOI18N
        findbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        findbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findbuttonMouseClicked(evt);
            }
        });
        findbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(findbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 30, 30));

        caribrgtxt.setBackground(new java.awt.Color(0, 0, 0));
        caribrgtxt.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        caribrgtxt.setForeground(new java.awt.Color(255, 255, 255));
        caribrgtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        caribrgtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        caribrgtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caribrgtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                caribrgtxtFocusLost(evt);
            }
        });
        caribrgtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caribrgtxtMouseClicked(evt);
            }
        });
        caribrgtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caribrgtxtActionPerformed(evt);
            }
        });
        caribrgtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caribrgtxtKeyReleased(evt);
            }
        });
        jPanel3.add(caribrgtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 360, 30));

        findbutton2.setBackground(new java.awt.Color(230, 230, 230));
        findbutton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/search_icon-icons.com_74128-picsay.png"))); // NOI18N
        findbutton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        findbutton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findbutton2MouseClicked(evt);
            }
        });
        findbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbutton2ActionPerformed(evt);
            }
        });
        jPanel3.add(findbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, 30));

        caribrgtxt1.setBackground(new java.awt.Color(0, 87, 118));
        caribrgtxt1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        caribrgtxt1.setForeground(new java.awt.Color(252, 249, 137));
        caribrgtxt1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        caribrgtxt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        caribrgtxt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caribrgtxt1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                caribrgtxt1FocusLost(evt);
            }
        });
        caribrgtxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caribrgtxt1MouseClicked(evt);
            }
        });
        caribrgtxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caribrgtxt1ActionPerformed(evt);
            }
        });
        caribrgtxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caribrgtxt1KeyReleased(evt);
            }
        });
        jPanel3.add(caribrgtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 180, 30));

        roundedPanel17.setBackground(new java.awt.Color(0, 87, 118));
        roundedPanel17.setRoundBottomLeft(15);
        roundedPanel17.setRoundBottomRight(15);
        roundedPanel17.setRoundTopLeft(15);
        roundedPanel17.setRoundTopRight(15);

        javax.swing.GroupLayout roundedPanel17Layout = new javax.swing.GroupLayout(roundedPanel17);
        roundedPanel17.setLayout(roundedPanel17Layout);
        roundedPanel17Layout.setHorizontalGroup(
            roundedPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        roundedPanel17Layout.setVerticalGroup(
            roundedPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(roundedPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 740, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setText("   DATA BARANG");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 40));

        roundedPanel16.setBackground(new java.awt.Color(252, 249, 137));
        roundedPanel16.setRoundBottomLeft(15);
        roundedPanel16.setRoundBottomRight(15);
        roundedPanel16.setRoundTopLeft(15);
        roundedPanel16.setRoundTopRight(15);

        javax.swing.GroupLayout roundedPanel16Layout = new javax.swing.GroupLayout(roundedPanel16);
        roundedPanel16.setLayout(roundedPanel16Layout);
        roundedPanel16Layout.setHorizontalGroup(
            roundedPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        roundedPanel16Layout.setVerticalGroup(
            roundedPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(roundedPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 740, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 1130, 80));

        jPanel8.setBackground(new java.awt.Color(0, 87, 118));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga Jual");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 20));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Expired");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 50, 20));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Barang");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 20));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID BARANG");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        namatxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jPanel8.add(namatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 180, -1));

        hargajualtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jPanel8.add(hargajualtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, -1));

        stoktxt.setEditable(false);
        stoktxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jPanel8.add(stoktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 70, -1));

        deletebutton.setBackground(new java.awt.Color(224, 25, 25));
        deletebutton.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        deletebutton.setForeground(new java.awt.Color(255, 255, 255));
        deletebutton.setText("Hapus");
        deletebutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deletebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletebuttonMouseEntered(evt);
            }
        });
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel8.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 80, 30));

        updatebutton.setBackground(new java.awt.Color(230, 230, 230));
        updatebutton.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        updatebutton.setText("Edit");
        updatebutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updatebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebuttonMouseClicked(evt);
            }
        });
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel8.add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 80, 30));

        addbutton.setBackground(new java.awt.Color(224, 25, 25));
        addbutton.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        addbutton.setForeground(new java.awt.Color(255, 255, 255));
        addbutton.setText("Simpan");
        addbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        jPanel8.add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 80, 30));

        refreshbtn.setBackground(new java.awt.Color(0, 0, 0));
        refreshbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refreshbtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshbtn.setText("BATAL");
        refreshbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });
        jPanel8.add(refreshbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 60, 30));

        idbrgtxt1.setEditable(false);
        idbrgtxt1.setBackground(new java.awt.Color(252, 249, 137));
        idbrgtxt1.setForeground(new java.awt.Color(0, 87, 118));
        idbrgtxt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        idbrgtxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbrgtxt1ActionPerformed(evt);
            }
        });
        jPanel8.add(idbrgtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 130, 20));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Harga Beli");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 20));

        hbtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(hbtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 180, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stok Barang");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 20));
        jPanel8.add(tanggalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 180, -1));

        tabel_barang.setBackground(new java.awt.Color(252, 249, 137));
        tabel_barang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabel_barang.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tabel_barang.setForeground(new java.awt.Color(0, 87, 118));
        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id_Barang", "Nama_Barang", "Harga_Jual", "Stok_Barang"
            }
        ));
        tabel_barang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        tabel_barang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabel_barangKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabel_barangKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_barang);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 700, 290));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 720, 550));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 0, 740, 640));

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/iconnew-picsay.png"))); // NOI18N
        jPanel33.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, -1));

        jLabel22.setBackground(new java.awt.Color(0, 87, 118));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 87, 118));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("   MAIN  MENU");
        jPanel33.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 20));

        roundedPanel13.setBackground(new java.awt.Color(0, 0, 0));
        roundedPanel13.setRoundBottomLeft(15);
        roundedPanel13.setRoundBottomRight(15);
        roundedPanel13.setRoundTopLeft(15);
        roundedPanel13.setRoundTopRight(15);
        roundedPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelexit.setBackground(new java.awt.Color(255, 255, 255));
        labelexit.setForeground(new java.awt.Color(255, 255, 255));
        labelexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/logoutnew().png"))); // NOI18N
        labelexit.setText("⟪⟪⟪");
        labelexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelexitMouseExited(evt);
            }
        });
        roundedPanel13.add(labelexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 30, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 87, 118));
        jLabel8.setText("DASHBOARD");
        roundedPanel13.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 180, 50));

        panellogout.setBackground(new java.awt.Color(0, 0, 0));
        panellogout.setRoundBottomLeft(15);
        panellogout.setRoundTopRight(15);

        javax.swing.GroupLayout panellogoutLayout = new javax.swing.GroupLayout(panellogout);
        panellogout.setLayout(panellogoutLayout);
        panellogoutLayout.setHorizontalGroup(
            panellogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panellogoutLayout.setVerticalGroup(
            panellogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        roundedPanel13.add(panellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 50, 50));

        paneldash.setBackground(new java.awt.Color(0, 0, 0));
        paneldash.setRoundBottomRight(15);
        paneldash.setRoundTopRight(15);

        labeltrans6.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans6.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans6.setText("DASHBOARD");
        labeltrans6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneldashLayout = new javax.swing.GroupLayout(paneldash);
        paneldash.setLayout(paneldashLayout);
        paneldashLayout.setHorizontalGroup(
            paneldashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        paneldashLayout.setVerticalGroup(
            paneldashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldashLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(paneldash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, -1));

        panellap.setBackground(new java.awt.Color(0, 0, 0));
        panellap.setRoundBottomRight(15);
        panellap.setRoundTopRight(15);

        labeltrans2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans2.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans2.setText("LAPORAN");
        labeltrans2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panellapLayout = new javax.swing.GroupLayout(panellap);
        panellap.setLayout(panellapLayout);
        panellapLayout.setHorizontalGroup(
            panellapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panellapLayout.setVerticalGroup(
            panellapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panellapLayout.createSequentialGroup()
                .addComponent(labeltrans2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        roundedPanel13.add(panellap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 20));

        panelkrwn.setBackground(new java.awt.Color(0, 0, 0));
        panelkrwn.setRoundBottomRight(15);
        panelkrwn.setRoundTopRight(15);

        labeltrans3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans3.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans3.setText("DATA KARYAWAN");
        labeltrans3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelkrwnLayout = new javax.swing.GroupLayout(panelkrwn);
        panelkrwn.setLayout(panelkrwnLayout);
        panelkrwnLayout.setHorizontalGroup(
            panelkrwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkrwnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans3)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelkrwnLayout.setVerticalGroup(
            panelkrwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelkrwnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(panelkrwn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 20));

        panelsup.setBackground(new java.awt.Color(0, 0, 0));
        panelsup.setRoundBottomRight(15);
        panelsup.setRoundTopRight(15);

        labeltrans5.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans5.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans5.setText("DATA SUPPLIER");
        labeltrans5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelsupLayout = new javax.swing.GroupLayout(panelsup);
        panelsup.setLayout(panelsupLayout);
        panelsupLayout.setHorizontalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans5)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelsupLayout.setVerticalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(panelsup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 20));

        panelrang.setBackground(new java.awt.Color(255, 255, 255));
        panelrang.setRoundBottomRight(15);
        panelrang.setRoundTopRight(15);

        labeltrans4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans4.setText("DATA BARANG");
        labeltrans4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelrangLayout = new javax.swing.GroupLayout(panelrang);
        panelrang.setLayout(panelrangLayout);
        panelrangLayout.setHorizontalGroup(
            panelrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans4)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        panelrangLayout.setVerticalGroup(
            panelrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelrangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(panelrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 20));

        paneltrans.setBackground(new java.awt.Color(0, 0, 0));
        paneltrans.setRoundBottomRight(15);
        paneltrans.setRoundTopRight(15);

        labeltrans1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans1.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans1.setText("TRANSAKSI");
        labeltrans1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneltransLayout = new javax.swing.GroupLayout(paneltrans);
        paneltrans.setLayout(paneltransLayout);
        paneltransLayout.setHorizontalGroup(
            paneltransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltransLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        paneltransLayout.setVerticalGroup(
            paneltransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltransLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(paneltrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 160, -1));

        jPanel33.add(roundedPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, 480));

        getContentPane().add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 640));

        setSize(new java.awt.Dimension(929, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void caribrgtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caribrgtxtKeyReleased

    }//GEN-LAST:event_caribrgtxtKeyReleased

    private void caribrgtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caribrgtxtActionPerformed

    }//GEN-LAST:event_caribrgtxtActionPerformed

    private void caribrgtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caribrgtxtMouseClicked

    }//GEN-LAST:event_caribrgtxtMouseClicked

    private void caribrgtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caribrgtxtFocusLost

    }//GEN-LAST:event_caribrgtxtFocusLost

    private void caribrgtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caribrgtxtFocusGained

    }//GEN-LAST:event_caribrgtxtFocusGained

    private void findbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbuttonActionPerformed

    }//GEN-LAST:event_findbuttonActionPerformed

    private void findbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findbuttonMouseClicked
        tampilkan_data();
    }//GEN-LAST:event_findbuttonMouseClicked

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        Kosongkan_form();
        otomatis();
    }//GEN-LAST:event_refreshbtnActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed

    }//GEN-LAST:event_deletebuttonActionPerformed

    private void deletebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebuttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebuttonMouseEntered

    private void deletebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebuttonMouseClicked
        //Fungsi untuk menghapus data dari tabel supplier berdasarkan kolom id_Barang
        int opt =  JOptionPane.showConfirmDialog
        (this, "Apakah Yakin Ingin Menghapus Data Ini?", "Hapus", JOptionPane.YES_NO_OPTION);
        if(opt == 0){ // JIka user memilih opsi "YES" maka data akan terhapus dan jika memilih opsi "NO" maka data akan batal terhapus
        try {
            String sql = "DELETE FROM barang WHERE id_Barang ='" + idbrgtxt1.getText() + "'";
            java.sql.Connection con = (Connection) Koneksi.configDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
        tampilkan_data();
        Kosongkan_form();
    }//GEN-LAST:event_deletebuttonMouseClicked

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed

    }//GEN-LAST:event_updatebuttonActionPerformed

    private void updatebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebuttonMouseClicked
       //Aksi yang digunakan untuk mengupdate data dari tabel barang 
      String tampilan = "yyyy-MM-dd";
      SimpleDateFormat sdf = new SimpleDateFormat(tampilan);
      String tgl = String.valueOf(sdf.format(tanggalan.getDate()));
      
        try {
            String sql = "INSERT barang SET id_Barang='" + idbrgtxt1.getText() + "' ,nama_Barang='" + namatxt.getText() 
                    + "' ,Harga_Jual='" + hargajualtxt.getText() + "' ,Harga_Beli='" + hbtxt.getText() + "' ,Stok_Barang='" + stoktxt.getText() 
                    +"' ,Expired='" + tgl + "' On Duplicate Key Update id_Barang ='" + idbrgtxt1.getText() + "' ,nama_Barang='" + namatxt.getText() 
                    + "' ,Harga_Jual='" + hargajualtxt.getText() + "' ,Harga_Beli='" + hbtxt.getText() + "' ,Stok_Barang='" + stoktxt.getText()
                    + "' ,Expired='" + tgl +"'";
            java.sql.Connection con = (Connection) Koneksi.configDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
        tampilkan_data();
        Kosongkan_form();
       
    }//GEN-LAST:event_updatebuttonMouseClicked

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
      //Aksi yang digunakan untuk menambah data ke dalam tabel barang
      String tampilan = "yyyy-MM-dd";
      SimpleDateFormat sdf = new SimpleDateFormat(tampilan);
      String tgl = String.valueOf(sdf.format(tanggalan.getDate()));
      
        try {
            String sql = "INSERT INTO barang VALUES ('" + idbrgtxt1.getText() + "','" + namatxt.getText() + "','" + hbtxt.getText() + "','" + hargajualtxt.getText() + "','" + stoktxt.getText() + "','"+ tgl +"')";
            java.sql.Connection con = (Connection) Koneksi.configDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Simpan Data Berhasil!");

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, " Simpan Data Gagal");
        }
        tampilkan_data();
        Kosongkan_form();
        otomatis();

    }//GEN-LAST:event_addbuttonActionPerformed

    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barangMouseClicked
        //Aksi yang digunakan untuk menampilkan data dari tabel_barang ke kolom text yang telah didefinisikan ketika salah satu baris diklik
        int baris = tabel_barang.rowAtPoint(evt.getPoint());
        String id = tabel_barang.getValueAt(baris, 1).toString();
        idbrgtxt1.setText(id);
        String nama = tabel_barang.getValueAt(baris, 2).toString();
        namatxt.setText(nama);
        String hj = tabel_barang.getValueAt(baris, 3).toString();
        hargajualtxt.setText(hj);
        String hb = tabel_barang.getValueAt(baris, 4).toString();
        hbtxt.setText(hb);
        String stok = tabel_barang.getValueAt(baris, 5).toString();
        stoktxt.setText(stok);
        tanggalan.setDate(gettgl(tabel_barang, 6));
     
        
    }//GEN-LAST:event_tabel_barangMouseClicked

    private void caribrgtxt1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caribrgtxt1FocusGained

    }//GEN-LAST:event_caribrgtxt1FocusGained

    private void caribrgtxt1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caribrgtxt1FocusLost

    }//GEN-LAST:event_caribrgtxt1FocusLost

    private void caribrgtxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caribrgtxt1MouseClicked

    }//GEN-LAST:event_caribrgtxt1MouseClicked

    private void caribrgtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caribrgtxt1ActionPerformed
tampilkan_data();
    }//GEN-LAST:event_caribrgtxt1ActionPerformed

    private void caribrgtxt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caribrgtxt1KeyReleased
tampilkan_data();
    }//GEN-LAST:event_caribrgtxt1KeyReleased

    private void findbutton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findbutton2MouseClicked
        tampilkan_data();
    }//GEN-LAST:event_findbutton2MouseClicked

    private void findbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbutton2ActionPerformed

    }//GEN-LAST:event_findbutton2ActionPerformed

    private void idbrgtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbrgtxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbrgtxt1ActionPerformed

    private void tanggalanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanggalanMouseClicked
        
    }//GEN-LAST:event_tanggalanMouseClicked

    private void labelexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexitMouseClicked
        Login2 login = new Login2();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelexitMouseClicked

    private void labelexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexitMouseEntered
        // TODO add your handling code here:
        labelexit.setForeground(Color.RED);
        panellogout.setBackground(Color.RED);
    }//GEN-LAST:event_labelexitMouseEntered

    private void labelexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexitMouseExited
        labelexit.setForeground(Color.WHITE);
        panellogout.setBackground(Color.BLACK);
    }//GEN-LAST:event_labelexitMouseExited

    private void labeltrans6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans6MouseClicked
try {
            Dashboard2 d = new Dashboard2();
            d.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(transaksi2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labeltrans6MouseClicked

    private void labeltrans6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans6MouseEntered
         labeltrans6.setForeground(Color.BLACK);
        paneldash.setBackground(Color.WHITE);

    }//GEN-LAST:event_labeltrans6MouseEntered

    private void labeltrans6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans6MouseExited
        labeltrans6.setForeground(Color.WHITE);
        paneldash.setBackground(Color.BLACK);

    }//GEN-LAST:event_labeltrans6MouseExited

    private void labeltrans2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans2MouseClicked
        // TODO add your handling code here:
        Laporan ran = new Laporan();
        ran.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labeltrans2MouseClicked

    private void labeltrans2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans2MouseEntered
        // TODO add your handling code here:
        labeltrans2.setForeground(Color.BLACK);
        panellap.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans2MouseEntered

    private void labeltrans2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans2MouseExited
        // TODO add your handling code here:
        labeltrans2.setForeground(Color.WHITE);
        panellap.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans2MouseExited

    private void labeltrans3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans3MouseClicked
        // TODO add your handling code here:
        pemasok3 sok = new pemasok3();
        sok.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labeltrans3MouseClicked

    private void labeltrans3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans3MouseEntered
        // TODO add your handling code here:
        labeltrans3.setForeground(Color.BLACK);
        panelkrwn.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans3MouseEntered

    private void labeltrans3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans3MouseExited
        // TODO add your handling code here:
        labeltrans3.setForeground(Color.WHITE);
        panelkrwn.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans3MouseExited

    private void labeltrans5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans5MouseClicked
        // TODO add your handling code here:
        supplier2 s = new supplier2();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labeltrans5MouseClicked

    private void labeltrans5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans5MouseEntered
        // TODO add your handling code here:
        labeltrans5.setForeground(Color.BLACK);
        panelsup.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans5MouseEntered

    private void labeltrans5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans5MouseExited
        // TODO add your handling code here:
        labeltrans5.setForeground(Color.WHITE);
        panelsup.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans5MouseExited

    private void labeltrans4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans4MouseClicked


    }//GEN-LAST:event_labeltrans4MouseClicked

    private void labeltrans4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans4MouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_labeltrans4MouseEntered

    private void labeltrans4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans4MouseExited
        // TODO add your handling code here:
      
    }//GEN-LAST:event_labeltrans4MouseExited

    private void labeltrans1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans1MouseClicked
        transaksi2 t = new transaksi2();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labeltrans1MouseClicked

    private void labeltrans1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans1MouseEntered
        labeltrans1.setForeground(Color.BLACK);
        paneltrans.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans1MouseEntered

    private void labeltrans1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans1MouseExited
        labeltrans1.setForeground(Color.WHITE);
        paneltrans.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans1MouseExited

    private void tabel_barangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabel_barangKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_barangKeyReleased

    private void tabel_barangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabel_barangKeyPressed
         
     
    }//GEN-LAST:event_tabel_barangKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new barang2().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(barang2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JTextField caribrgtxt;
    private javax.swing.JTextField caribrgtxt1;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton findbutton;
    private javax.swing.JButton findbutton2;
    private javax.swing.JTextField hargajualtxt;
    private javax.swing.JTextField hbtxt;
    private javax.swing.JTextField idbrgtxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelexit;
    private javax.swing.JLabel labeltrans1;
    private javax.swing.JLabel labeltrans2;
    private javax.swing.JLabel labeltrans3;
    private javax.swing.JLabel labeltrans4;
    private javax.swing.JLabel labeltrans5;
    private javax.swing.JLabel labeltrans6;
    private javax.swing.JTextField namatxt;
    private org.hq.RoundedPanel paneldash;
    private org.hq.RoundedPanel panelkrwn;
    private org.hq.RoundedPanel panellap;
    private org.hq.RoundedPanel panellogout;
    private org.hq.RoundedPanel panelrang;
    private org.hq.RoundedPanel panelsup;
    private org.hq.RoundedPanel paneltrans;
    private javax.swing.JButton refreshbtn;
    private org.hq.RoundedPanel roundedPanel13;
    private org.hq.RoundedPanel roundedPanel16;
    private org.hq.RoundedPanel roundedPanel17;
    private javax.swing.JTextField stoktxt;
    private javax.swing.JTable tabel_barang;
    private com.toedter.calendar.JDateChooser tanggalan;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
