
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Lilik Aliyawati
 */
public class Laporan extends javax.swing.JFrame {

    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        roundedPanel9 = new org.hq.RoundedPanel();
        roundedPanel10 = new org.hq.RoundedPanel();
        roundedPanel6 = new org.hq.RoundedPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panelbeli = new org.hq.RoundedPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panely = new org.hq.RoundedPanel();
        roundedPanel5 = new org.hq.RoundedPanel();
        paneljual = new org.hq.RoundedPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelx = new org.hq.RoundedPanel();
        roundedPanel3 = new org.hq.RoundedPanel();
        roundedPanel8 = new org.hq.RoundedPanel();
        roundedPanel7 = new org.hq.RoundedPanel();
        jSeparator1 = new javax.swing.JSeparator();
        roundedPanel12 = new org.hq.RoundedPanel();
        jPanel35 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        roundedPanel16 = new org.hq.RoundedPanel();
        roundedPanel17 = new org.hq.RoundedPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        roundedPanel13 = new org.hq.RoundedPanel();
        labelexit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panellogout = new org.hq.RoundedPanel();
        paneldash = new org.hq.RoundedPanel();
        labeltrans6 = new javax.swing.JLabel();
        panellap = new org.hq.RoundedPanel();
        labeltrans2 = new javax.swing.JLabel();
        panelkrwn = new org.hq.RoundedPanel();
        labeltrans3 = new javax.swing.JLabel();
        panelsup = new org.hq.RoundedPanel();
        labeltrans5 = new javax.swing.JLabel();
        panelrang = new org.hq.RoundedPanel();
        labeltrans4 = new javax.swing.JLabel();
        paneltrans = new org.hq.RoundedPanel();
        labeltrans1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(949, 748));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel32.setBackground(new java.awt.Color(252, 249, 137));
        jPanel3.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 20, 290));

        roundedPanel9.setBackground(new java.awt.Color(252, 249, 137));
        roundedPanel9.setRoundTopLeft(20);
        roundedPanel9.setRoundTopRight(20);
        roundedPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout roundedPanel10Layout = new javax.swing.GroupLayout(roundedPanel10);
        roundedPanel10.setLayout(roundedPanel10Layout);
        roundedPanel10Layout.setHorizontalGroup(
            roundedPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        roundedPanel10Layout.setVerticalGroup(
            roundedPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        roundedPanel9.add(roundedPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -20, -1, 20));

        jPanel3.add(roundedPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 240, 10));

        roundedPanel6.setBackground(new java.awt.Color(252, 249, 137));
        roundedPanel6.setRoundTopLeft(15);
        roundedPanel6.setRoundTopRight(15);
        roundedPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(roundedPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 400, 10));

        jPanel15.setBackground(new java.awt.Color(252, 249, 137));
        jPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, 20));

        jPanel4.setBackground(new java.awt.Color(252, 249, 137));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, 20));

        panelbeli.setBackground(new java.awt.Color(255, 255, 255));
        panelbeli.setRoundBottomLeft(20);
        panelbeli.setRoundTopRight(20);

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(23, 176, 151));
        jLabel14.setText("LAPORAN");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(23, 176, 151));
        jLabel11.setText("PEMBELIAN");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        panely.setBackground(new java.awt.Color(0, 0, 0));
        panely.setRoundTopRight(15);

        javax.swing.GroupLayout panelyLayout = new javax.swing.GroupLayout(panely);
        panely.setLayout(panelyLayout);
        panelyLayout.setHorizontalGroup(
            panelyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panelyLayout.setVerticalGroup(
            panelyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        roundedPanel5.setBackground(new java.awt.Color(23, 176, 151));
        roundedPanel5.setForeground(new java.awt.Color(255, 200, 78));
        roundedPanel5.setRoundBottomLeft(15);

        javax.swing.GroupLayout roundedPanel5Layout = new javax.swing.GroupLayout(roundedPanel5);
        roundedPanel5.setLayout(roundedPanel5Layout);
        roundedPanel5Layout.setHorizontalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        roundedPanel5Layout.setVerticalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelbeliLayout = new javax.swing.GroupLayout(panelbeli);
        panelbeli.setLayout(panelbeliLayout);
        panelbeliLayout.setHorizontalGroup(
            panelbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbeliLayout.createSequentialGroup()
                .addGroup(panelbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbeliLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelbeliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(roundedPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panely, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        panelbeliLayout.setVerticalGroup(
            panelbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbeliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbeliLayout.createSequentialGroup()
                        .addComponent(panely, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelbeliLayout.createSequentialGroup()
                        .addGroup(panelbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelbeliLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(roundedPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        jPanel3.add(panelbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, 120));

        paneljual.setBackground(new java.awt.Color(255, 255, 255));
        paneljual.setRoundBottomLeft(20);
        paneljual.setRoundTopRight(20);

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 200, 78));
        jLabel13.setText("LAPORAN");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 200, 78));
        jLabel10.setText("PENJUALAN");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        panelx.setBackground(new java.awt.Color(0, 0, 0));
        panelx.setRoundTopRight(15);

        javax.swing.GroupLayout panelxLayout = new javax.swing.GroupLayout(panelx);
        panelx.setLayout(panelxLayout);
        panelxLayout.setHorizontalGroup(
            panelxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panelxLayout.setVerticalGroup(
            panelxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        roundedPanel3.setBackground(new java.awt.Color(255, 200, 78));
        roundedPanel3.setForeground(new java.awt.Color(255, 200, 78));
        roundedPanel3.setRoundBottomLeft(15);

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout paneljualLayout = new javax.swing.GroupLayout(paneljual);
        paneljual.setLayout(paneljualLayout);
        paneljualLayout.setHorizontalGroup(
            paneljualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneljualLayout.createSequentialGroup()
                .addGroup(paneljualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneljualLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(paneljualLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        paneljualLayout.setVerticalGroup(
            paneljualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneljualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneljualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneljualLayout.createSequentialGroup()
                        .addComponent(panelx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneljualLayout.createSequentialGroup()
                        .addGroup(paneljualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneljualLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        jPanel3.add(paneljual, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 190, 120));

        roundedPanel8.setBackground(new java.awt.Color(252, 249, 137));
        roundedPanel8.setRoundBottomLeft(15);
        roundedPanel8.setRoundBottomRight(15);
        roundedPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(roundedPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 190, 10));

        roundedPanel7.setBackground(new java.awt.Color(252, 249, 137));
        roundedPanel7.setRoundBottomLeft(15);
        roundedPanel7.setRoundBottomRight(15);
        roundedPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(roundedPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 190, 10));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 10, 560));

        roundedPanel12.setBackground(new java.awt.Color(0, 87, 118));
        roundedPanel12.setRoundBottomLeft(15);
        roundedPanel12.setRoundBottomRight(15);
        roundedPanel12.setRoundTopLeft(15);
        roundedPanel12.setRoundTopRight(15);

        javax.swing.GroupLayout roundedPanel12Layout = new javax.swing.GroupLayout(roundedPanel12);
        roundedPanel12.setLayout(roundedPanel12Layout);
        roundedPanel12Layout.setHorizontalGroup(
            roundedPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        roundedPanel12Layout.setVerticalGroup(
            roundedPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel3.add(roundedPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 720, 530));

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 87, 118));
        jLabel3.setText("LAPORAN");

        roundedPanel16.setBackground(new java.awt.Color(252, 249, 137));
        roundedPanel16.setRoundBottomLeft(15);
        roundedPanel16.setRoundBottomRight(15);
        roundedPanel16.setRoundTopLeft(15);
        roundedPanel16.setRoundTopRight(15);

        javax.swing.GroupLayout roundedPanel16Layout = new javax.swing.GroupLayout(roundedPanel16);
        roundedPanel16.setLayout(roundedPanel16Layout);
        roundedPanel16Layout.setHorizontalGroup(
            roundedPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundedPanel16Layout.setVerticalGroup(
            roundedPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        roundedPanel17.setBackground(new java.awt.Color(0, 87, 118));
        roundedPanel17.setRoundBottomLeft(15);
        roundedPanel17.setRoundBottomRight(15);
        roundedPanel17.setRoundTopLeft(15);
        roundedPanel17.setRoundTopRight(15);

        javax.swing.GroupLayout roundedPanel17Layout = new javax.swing.GroupLayout(roundedPanel17);
        roundedPanel17.setLayout(roundedPanel17Layout);
        roundedPanel17Layout.setHorizontalGroup(
            roundedPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundedPanel17Layout.setVerticalGroup(
            roundedPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(270, 270, 270))
            .addComponent(roundedPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(roundedPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(roundedPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(roundedPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 80));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 0, 740, 630));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/iconnew-picsay.png"))); // NOI18N
        jPanel21.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, -1));

        jLabel22.setBackground(new java.awt.Color(0, 87, 118));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 87, 118));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("   MAIN  MENU");
        jPanel21.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 20));

        roundedPanel13.setBackground(new java.awt.Color(0, 0, 0));
        roundedPanel13.setRoundBottomLeft(15);
        roundedPanel13.setRoundBottomRight(15);
        roundedPanel13.setRoundTopLeft(15);
        roundedPanel13.setRoundTopRight(15);
        roundedPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelexit.setBackground(new java.awt.Color(255, 255, 255));
        labelexit.setForeground(new java.awt.Color(255, 255, 255));
        labelexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/logoutnew().png"))); // NOI18N
        labelexit.setText("⟪⟪⟪");
        labelexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelexitMouseExited(evt);
            }
        });
        roundedPanel13.add(labelexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 30, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 87, 118));
        jLabel7.setText("DASHBOARD");
        roundedPanel13.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 180, 50));

        panellogout.setBackground(new java.awt.Color(0, 0, 0));
        panellogout.setRoundBottomLeft(15);
        panellogout.setRoundTopRight(15);

        javax.swing.GroupLayout panellogoutLayout = new javax.swing.GroupLayout(panellogout);
        panellogout.setLayout(panellogoutLayout);
        panellogoutLayout.setHorizontalGroup(
            panellogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panellogoutLayout.setVerticalGroup(
            panellogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        roundedPanel13.add(panellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 50, 50));

        paneldash.setBackground(new java.awt.Color(0, 0, 0));
        paneldash.setRoundBottomRight(15);
        paneldash.setRoundTopRight(15);

        labeltrans6.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans6.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans6.setText("DASHBOARD");
        labeltrans6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneldashLayout = new javax.swing.GroupLayout(paneldash);
        paneldash.setLayout(paneldashLayout);
        paneldashLayout.setHorizontalGroup(
            paneldashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        paneldashLayout.setVerticalGroup(
            paneldashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldashLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(paneldash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, -1));

        panellap.setBackground(new java.awt.Color(255, 255, 255));
        panellap.setRoundBottomRight(15);
        panellap.setRoundTopRight(15);

        labeltrans2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans2.setText("LAPORAN");
        labeltrans2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panellapLayout = new javax.swing.GroupLayout(panellap);
        panellap.setLayout(panellapLayout);
        panellapLayout.setHorizontalGroup(
            panellapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panellapLayout.setVerticalGroup(
            panellapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panellapLayout.createSequentialGroup()
                .addComponent(labeltrans2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        roundedPanel13.add(panellap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 20));

        panelkrwn.setBackground(new java.awt.Color(0, 0, 0));
        panelkrwn.setRoundBottomRight(15);
        panelkrwn.setRoundTopRight(15);

        labeltrans3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans3.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans3.setText("DATA KARYAWAN");
        labeltrans3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelkrwnLayout = new javax.swing.GroupLayout(panelkrwn);
        panelkrwn.setLayout(panelkrwnLayout);
        panelkrwnLayout.setHorizontalGroup(
            panelkrwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkrwnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans3)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelkrwnLayout.setVerticalGroup(
            panelkrwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelkrwnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(panelkrwn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 20));

        panelsup.setBackground(new java.awt.Color(0, 0, 0));
        panelsup.setRoundBottomRight(15);
        panelsup.setRoundTopRight(15);

        labeltrans5.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans5.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans5.setText("DATA SUPPLIER");
        labeltrans5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelsupLayout = new javax.swing.GroupLayout(panelsup);
        panelsup.setLayout(panelsupLayout);
        panelsupLayout.setHorizontalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans5)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelsupLayout.setVerticalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(panelsup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 20));

        panelrang.setBackground(new java.awt.Color(0, 0, 0));
        panelrang.setRoundBottomRight(15);
        panelrang.setRoundTopRight(15);

        labeltrans4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans4.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans4.setText("DATA BARANG");
        labeltrans4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelrangLayout = new javax.swing.GroupLayout(panelrang);
        panelrang.setLayout(panelrangLayout);
        panelrangLayout.setHorizontalGroup(
            panelrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans4)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        panelrangLayout.setVerticalGroup(
            panelrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelrangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(panelrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 20));

        paneltrans.setBackground(new java.awt.Color(0, 0, 0));
        paneltrans.setRoundBottomRight(15);
        paneltrans.setRoundTopRight(15);

        labeltrans1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans1.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans1.setText("TRANSAKSI");
        labeltrans1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneltransLayout = new javax.swing.GroupLayout(paneltrans);
        paneltrans.setLayout(paneltransLayout);
        paneltransLayout.setHorizontalGroup(
            paneltransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltransLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        paneltransLayout.setVerticalGroup(
            paneltransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltransLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(paneltrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 160, -1));

        jPanel21.add(roundedPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, 480));

        getContentPane().add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 630));

        setSize(new java.awt.Dimension(929, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
        paneljual.setBackground(Color.WHITE);
        panelx.setBackground(Color.BLACK);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        paneljual.setBackground(Color.BLACK);
        panelx.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        try {
            // TODO add your handling code here:
            laporan_jual al = new laporan_jual();
            al.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
        paneljual.setBackground(Color.WHITE);
        panelx.setBackground(Color.BLACK);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        paneljual.setBackground(Color.BLACK);
        panelx.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        try {
            // TODO add your handling code here:
            laporan_jual al = new laporan_jual();
            al.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
        panelbeli.setBackground(Color.WHITE);
        panely.setBackground(Color.BLACK);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
        panely.setBackground(Color.WHITE);
        panelbeli.setBackground(Color.BLACK);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        try {
            // TODO add your handling code here:
            laporan_beli li = new laporan_beli();
            li.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
        panelbeli.setBackground(Color.WHITE);
        panely.setBackground(Color.BLACK);
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
        panelbeli.setBackground(Color.BLACK);
        panely.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        try {
            // TODO add your handling code here:
            laporan_beli li = new laporan_beli();
            li.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void labelexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexitMouseClicked
        Login2 login = new Login2();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelexitMouseClicked

    private void labelexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexitMouseEntered
        // TODO add your handling code here:
        labelexit.setForeground(Color.RED);
        panellogout.setBackground(Color.RED);
    }//GEN-LAST:event_labelexitMouseEntered

    private void labelexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexitMouseExited
        labelexit.setForeground(Color.WHITE);
        panellogout.setBackground(Color.BLACK);
    }//GEN-LAST:event_labelexitMouseExited

    private void labeltrans6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans6MouseClicked
        try {
            Dashboard2 d = new Dashboard2();
            d.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(transaksi2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labeltrans6MouseClicked

    private void labeltrans6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans6MouseEntered
         labeltrans6.setForeground(Color.BLACK);
        paneldash.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans6MouseEntered

    private void labeltrans6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans6MouseExited
         labeltrans6.setForeground(Color.WHITE);
        paneldash.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans6MouseExited

    private void labeltrans2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans2MouseClicked

    }//GEN-LAST:event_labeltrans2MouseClicked

    private void labeltrans2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans2MouseEntered

    }//GEN-LAST:event_labeltrans2MouseEntered

    private void labeltrans2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans2MouseExited

    }//GEN-LAST:event_labeltrans2MouseExited

    private void labeltrans3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans3MouseClicked
        // TODO add your handling code here:
        pemasok3 sok = new pemasok3();
        sok.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labeltrans3MouseClicked

    private void labeltrans3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans3MouseEntered
        // TODO add your handling code here:
        labeltrans3.setForeground(Color.BLACK);
        panelkrwn.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans3MouseEntered

    private void labeltrans3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans3MouseExited
        // TODO add your handling code here:
        labeltrans3.setForeground(Color.WHITE);
        panelkrwn.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans3MouseExited

    private void labeltrans5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans5MouseClicked
        // TODO add your handling code here:
        supplier2 s = new supplier2();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labeltrans5MouseClicked

    private void labeltrans5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans5MouseEntered
        // TODO add your handling code here:
        labeltrans5.setForeground(Color.BLACK);
        panelsup.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans5MouseEntered

    private void labeltrans5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans5MouseExited
        // TODO add your handling code here:
        labeltrans5.setForeground(Color.WHITE);
        panelsup.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans5MouseExited

    private void labeltrans4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans4MouseClicked

        try {
            // TODO add your handling code here:
            barang2 rg = new barang2();
            rg.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_labeltrans4MouseClicked

    private void labeltrans4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans4MouseEntered
        // TODO add your handling code here:
        labeltrans4.setForeground(Color.BLACK);
        panelrang.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans4MouseEntered

    private void labeltrans4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans4MouseExited
        // TODO add your handling code here:
        labeltrans4.setForeground(Color.WHITE);
        panelrang.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans4MouseExited

    private void labeltrans1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans1MouseClicked
        transaksi2 t = new transaksi2();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labeltrans1MouseClicked

    private void labeltrans1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans1MouseEntered
        labeltrans1.setForeground(Color.BLACK);
        paneltrans.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans1MouseEntered

    private void labeltrans1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans1MouseExited
        labeltrans1.setForeground(Color.WHITE);
        paneltrans.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelexit;
    private javax.swing.JLabel labeltrans1;
    private javax.swing.JLabel labeltrans2;
    private javax.swing.JLabel labeltrans3;
    private javax.swing.JLabel labeltrans4;
    private javax.swing.JLabel labeltrans5;
    private javax.swing.JLabel labeltrans6;
    private org.hq.RoundedPanel panelbeli;
    private org.hq.RoundedPanel paneldash;
    private org.hq.RoundedPanel paneljual;
    private org.hq.RoundedPanel panelkrwn;
    private org.hq.RoundedPanel panellap;
    private org.hq.RoundedPanel panellogout;
    private org.hq.RoundedPanel panelrang;
    private org.hq.RoundedPanel panelsup;
    private org.hq.RoundedPanel paneltrans;
    private org.hq.RoundedPanel panelx;
    private org.hq.RoundedPanel panely;
    private org.hq.RoundedPanel roundedPanel10;
    private org.hq.RoundedPanel roundedPanel12;
    private org.hq.RoundedPanel roundedPanel13;
    private org.hq.RoundedPanel roundedPanel16;
    private org.hq.RoundedPanel roundedPanel17;
    private org.hq.RoundedPanel roundedPanel3;
    private org.hq.RoundedPanel roundedPanel5;
    private org.hq.RoundedPanel roundedPanel6;
    private org.hq.RoundedPanel roundedPanel7;
    private org.hq.RoundedPanel roundedPanel8;
    private org.hq.RoundedPanel roundedPanel9;
    // End of variables declaration//GEN-END:variables
}
