 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import static base.barang2.gettgl;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
public class laporan_jual extends javax.swing.JFrame {

   public void tampil_data(String d1, String d2) throws SQLException{
       //Menampilkan data dari database laporan_beli ke tabel laporan harian (pembelian)
          Connection con = (Connection) Koneksi.configDB();
          PreparedStatement stm ;
          ResultSet res ;
                 
         try{
             
             if(d1.equals("") || d2.equals("")){
                 stm = con.prepareStatement("SELECT * FROM `laporan_jual`");
             }else{
                 stm = con.prepareStatement("SELECT * FROM `laporan_jual` WHERE `Tanggal` BETWEEN ? AND ?");
                 stm.setString(1, d1);
                 stm.setString(2, d2);
             }
             res = stm.executeQuery();
             DefaultTableModel model = (DefaultTableModel)tabelharian.getModel();
             Object[] row;
             
             while(res.next()){
                  row = new Object[8];
                  
                  row [0] = res.getString(1);
                  row [1] = res.getString(2);
                  row [2] = res.getString(3);
                  row [3] = res.getInt(4);
                  row [4] = res.getInt(5);
                  row [5] = res.getInt(6);
                  row [6] = res.getString(7);
                  row [7] = res.getDate(8);
                  model.addRow(row);
             }
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
   }
   
  public void tampil_data2(String d1, String d2) throws SQLException{
       //Menampilkan data dari database laporan_bulanan ke tabel laporan bulanan (pembelian)
         Connection con = (Connection) Koneksi.configDB();
          PreparedStatement stm ;
          ResultSet res ;
                 
         try{
             
             if(d1.equals("") || d2.equals("")){
                 stm = con.prepareStatement("SELECT * FROM `laporan_jual`");
             }else{
                 stm = con.prepareStatement("SELECT * FROM `laporan_jual` WHERE `Tanggal` BETWEEN ? AND ?");
                 stm.setString(1, d1);
                 stm.setString(2, d2);
             }
             res = stm.executeQuery();
             DefaultTableModel model = (DefaultTableModel)tabelbulanan.getModel();
             Object[] row;
             
             while(res.next()){
                  row = new Object[8];
                                 
                  row [0] = res.getString(1);
                  row [1] = res.getString(2);
                  row [2] = res.getString(3);
                  row [3] = res.getInt(4);
                  row [4] = res.getInt(5);
                  row [5] = res.getInt(6);
                  row [6] = res.getString(7);
                  row [7] = res.getDate(8);
                  model.addRow(row);
             }
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
   }
   
    public laporan_jual() throws SQLException  {
       initComponents();
       tampil_data("", "");
       tampil_data2("", "");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        backbutton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbulanan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelharian = new javax.swing.JTable();
        findbutton1 = new javax.swing.JButton();
        caribrgtxt1 = new javax.swing.JTextField();
        findbutton2 = new javax.swing.JButton();
        caribrgtxt2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        notranstxt = new javax.swing.JTextField();
        idbrgtxt = new javax.swing.JTextField();
        namatxt = new javax.swing.JTextField();
        jumlahtxt = new javax.swing.JTextField();
        hjtxt = new javax.swing.JTextField();
        totaltxt = new javax.swing.JTextField();
        jenistxt = new javax.swing.JTextField();
        tgltxt = new javax.swing.JTextField();
        tanggalan = new com.toedter.calendar.JDateChooser();
        tanggalan1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        tanggal1 = new com.toedter.calendar.JDateChooser();
        tanggal2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jScrollPane3.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 87, 118));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(252, 249, 137));
        jLabel29.setText("LAPORAN PENJUALAN");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        backbutton.setBackground(new java.awt.Color(0, 0, 0));
        backbutton.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        backbutton.setForeground(new java.awt.Color(255, 255, 255));
        backbutton.setText("«");
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backbuttonMouseExited(evt);
            }
        });
        jPanel1.add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 30, 30));

        tabelbulanan.setBackground(new java.awt.Color(252, 249, 137));
        tabelbulanan.setForeground(new java.awt.Color(0, 87, 118));
        tabelbulanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Transaksi", "Id Barang", "Nama Barang", "Jumlah", "Harga Jual", "Total", "Jenis Pembayaran", "Tanggal"
            }
        ));
        tabelbulanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbulananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelbulanan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 1010, 200));

        tabelharian.setBackground(new java.awt.Color(252, 249, 137));
        tabelharian.setForeground(new java.awt.Color(0, 87, 118));
        tabelharian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Transaksi", "Id Barang", "Nama Barang", "Jumlah", "Harga Jual", "Total", "Jenis Pembayaran", "Tanggal"
            }
        ));
        tabelharian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelharianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelharian);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 1010, 190));

        findbutton1.setBackground(new java.awt.Color(230, 230, 230));
        findbutton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/search_icon-icons.com_74128-picsay.png"))); // NOI18N
        findbutton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        findbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findbutton1MouseClicked(evt);
            }
        });
        findbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbutton1ActionPerformed(evt);
            }
        });
        jPanel1.add(findbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, 30));

        caribrgtxt1.setBackground(new java.awt.Color(250, 250, 250));
        caribrgtxt1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        caribrgtxt1.setForeground(new java.awt.Color(153, 153, 153));
        caribrgtxt1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        caribrgtxt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        caribrgtxt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caribrgtxt1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                caribrgtxt1FocusLost(evt);
            }
        });
        caribrgtxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caribrgtxt1MouseClicked(evt);
            }
        });
        caribrgtxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caribrgtxt1ActionPerformed(evt);
            }
        });
        caribrgtxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caribrgtxt1KeyReleased(evt);
            }
        });
        jPanel1.add(caribrgtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 180, 30));

        findbutton2.setBackground(new java.awt.Color(230, 230, 230));
        findbutton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/search_icon-icons.com_74128-picsay.png"))); // NOI18N
        findbutton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        findbutton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findbutton2MouseClicked(evt);
            }
        });
        findbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbutton2ActionPerformed(evt);
            }
        });
        jPanel1.add(findbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, 30));

        caribrgtxt2.setBackground(new java.awt.Color(250, 250, 250));
        caribrgtxt2.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        caribrgtxt2.setForeground(new java.awt.Color(153, 153, 153));
        caribrgtxt2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        caribrgtxt2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        caribrgtxt2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caribrgtxt2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                caribrgtxt2FocusLost(evt);
            }
        });
        caribrgtxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caribrgtxt2MouseClicked(evt);
            }
        });
        caribrgtxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caribrgtxt2ActionPerformed(evt);
            }
        });
        caribrgtxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caribrgtxt2KeyReleased(evt);
            }
        });
        jPanel1.add(caribrgtxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 180, 30));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 10, 560));
        jPanel1.add(notranstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, -1, -1));
        jPanel1.add(idbrgtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, -1, -1));

        namatxt.setText("jTextField1");
        jPanel1.add(namatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, -1, -1));

        jumlahtxt.setText("jTextField1");
        jPanel1.add(jumlahtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, -1, -1));

        hjtxt.setText("jTextField1");
        hjtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hjtxtActionPerformed(evt);
            }
        });
        jPanel1.add(hjtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, -1, -1));

        totaltxt.setText("jTextField1");
        jPanel1.add(totaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 260, -1, -1));

        jenistxt.setText("jTextField1");
        jPanel1.add(jenistxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, -1, -1));

        tgltxt.setText("jTextField1");
        jPanel1.add(tgltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 80, -1));

        tanggalan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanggalanMouseClicked(evt);
            }
        });
        jPanel1.add(tanggalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 170, 30));

        tanggalan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanggalan1MouseClicked(evt);
            }
        });
        jPanel1.add(tanggalan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 170, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(252, 249, 137));
        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 60, 30));
        jPanel1.add(tanggal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 170, 30));
        jPanel1.add(tanggal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 170, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(252, 249, 137));
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 60, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(252, 249, 137));
        jLabel5.setText("HARIAN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 249, 137));
        jLabel2.setText("BULANAN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, 180, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Batal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 60, 30));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 60, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/transaksi_beli_logo.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 650, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 630));

        setSize(new java.awt.Dimension(1099, 625));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        Laporan board = new Laporan();
        board.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_backbuttonMouseClicked

    private void tabelharianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelharianMouseClicked
       
    }//GEN-LAST:event_tabelharianMouseClicked

    private void tabelbulananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbulananMouseClicked

    }//GEN-LAST:event_tabelbulananMouseClicked

    private void findbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbutton1ActionPerformed

    }//GEN-LAST:event_findbutton1ActionPerformed

    private void findbutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findbutton1MouseClicked

    }//GEN-LAST:event_findbutton1MouseClicked

    private void caribrgtxt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caribrgtxt1KeyReleased

    }//GEN-LAST:event_caribrgtxt1KeyReleased

    private void caribrgtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caribrgtxt1ActionPerformed

    }//GEN-LAST:event_caribrgtxt1ActionPerformed

    private void caribrgtxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caribrgtxt1MouseClicked

    }//GEN-LAST:event_caribrgtxt1MouseClicked

    private void caribrgtxt1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caribrgtxt1FocusLost

    }//GEN-LAST:event_caribrgtxt1FocusLost

    private void caribrgtxt1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caribrgtxt1FocusGained

    }//GEN-LAST:event_caribrgtxt1FocusGained

    private void findbutton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findbutton2MouseClicked
       
    }//GEN-LAST:event_findbutton2MouseClicked

    private void findbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbutton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findbutton2ActionPerformed

    private void caribrgtxt2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caribrgtxt2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_caribrgtxt2FocusGained

    private void caribrgtxt2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caribrgtxt2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_caribrgtxt2FocusLost

    private void caribrgtxt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caribrgtxt2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_caribrgtxt2MouseClicked

    private void caribrgtxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caribrgtxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caribrgtxt2ActionPerformed

    private void caribrgtxt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caribrgtxt2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_caribrgtxt2KeyReleased

    private void backbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseExited
        // TODO add your handling code here:
        backbutton.setForeground(Color.WHITE);
    }//GEN-LAST:event_backbuttonMouseExited

    private void backbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseEntered
        // TODO add your handling code here:
        backbutton.setForeground(Color.YELLOW);
    }//GEN-LAST:event_backbuttonMouseEntered

    private void hjtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hjtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hjtxtActionPerformed

    private void tanggalanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanggalanMouseClicked

    }//GEN-LAST:event_tanggalanMouseClicked

    private void tanggalan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanggalan1MouseClicked

    }//GEN-LAST:event_tanggalan1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            tabelharian.setModel(new DefaultTableModel(null, new Object[]{"No_Transaksi", "ID_Barang", "Nama_Barang", "Jumlah", "Harga_Beli", "Total", "Jenis_Pembayaran", "Tanggal"}));
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            String date1 = date.format(tanggalan.getDate());
            String date2 = date.format(tanggalan1.getDate());

            tampil_data(date1, date2);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            tabelbulanan.setModel(new DefaultTableModel(null, new Object[]{"No_Transaksi", "ID_Barang", "Nama_Barang", "Jumlah", "Harga_Beli", "Total", "Jenis_Pembayaran", "Tanggal"}));
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            String date1 = date.format(tanggal1.getDate());
            String date2 = date.format(tanggal2.getDate());

            tampil_data2(date1, date2);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try {
           tampil_data("", "");
       } catch (SQLException ex) {
           Logger.getLogger(laporan_jual.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try {
           tampil_data2("", "");
       } catch (SQLException ex) {
           Logger.getLogger(laporan_jual.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan_jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan_jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan_jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan_jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new laporan_jual().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(laporan_jual.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backbutton;
    private javax.swing.JTextField caribrgtxt1;
    private javax.swing.JTextField caribrgtxt2;
    private javax.swing.JButton findbutton1;
    private javax.swing.JButton findbutton2;
    private javax.swing.JTextField hjtxt;
    private javax.swing.JTextField idbrgtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField jenistxt;
    private javax.swing.JTextField jumlahtxt;
    private javax.swing.JTextField namatxt;
    private javax.swing.JTextField notranstxt;
    private javax.swing.JTable tabelbulanan;
    private javax.swing.JTable tabelharian;
    private com.toedter.calendar.JDateChooser tanggal1;
    private com.toedter.calendar.JDateChooser tanggal2;
    private com.toedter.calendar.JDateChooser tanggalan;
    private com.toedter.calendar.JDateChooser tanggalan1;
    private javax.swing.JTextField tgltxt;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables
}
   
