/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
public class Login2 extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public Login2() {
        initComponents();
        panellogin.setFocusable(true);
        this.picek.setVisible(false);
          line.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelmin = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelx = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panellogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputtxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        melek = new javax.swing.JLabel();
        picek = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passtxt = new javax.swing.JPasswordField();
        forgotlabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        line = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(252, 249, 137));
        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        jPanel2.setBackground(new java.awt.Color(0, 87, 118));
        jPanel2.setForeground(new java.awt.Color(224, 25, 25));
        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 450));

        panelmin.setBackground(new java.awt.Color(255, 255, 255));
        panelmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelminMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("—");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelminLayout = new javax.swing.GroupLayout(panelmin);
        panelmin.setLayout(panelminLayout);
        panelminLayout.setHorizontalGroup(
            panelminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelminLayout.setVerticalGroup(
            panelminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelminLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(panelmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 30, 30));

        panelx.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText(" X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelxLayout = new javax.swing.GroupLayout(panelx);
        panelx.setLayout(panelxLayout);
        panelxLayout.setHorizontalGroup(
            panelxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelxLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelxLayout.setVerticalGroup(
            panelxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.add(panelx, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/iconnew-picsay.png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 87, 118));
        jLabel8.setText("  Aplikasi Pembukuan UMKM");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 200, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 87, 118));
        jLabel11.setText("   ELLI SHOP");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 150, -1));

        jLabel5.setForeground(new java.awt.Color(0, 87, 118));
        jLabel5.setText("   Author k5tifc");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 90, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 400, 450));

        panellogin.setBackground(new java.awt.Color(0, 87, 118));
        panellogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        panellogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        panellogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, -1));

        inputtxt.setBackground(new java.awt.Color(0, 0, 0));
        inputtxt.setForeground(new java.awt.Color(252, 249, 137));
        inputtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputtxt.setToolTipText("Masukkan Username");
        inputtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inputtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputtxtFocusLost(evt);
            }
        });
        inputtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputtxtActionPerformed(evt);
            }
        });
        panellogin.add(inputtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 180, 30));

        jButton1.setBackground(new java.awt.Color(252, 249, 137));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 87, 118));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panellogin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 70, 20));

        jButton2.setBackground(new java.awt.Color(252, 249, 137));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 87, 118));
        jButton2.setText("REGISTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panellogin.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 90, 20));

        melek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/visible.jpg"))); // NOI18N
        melek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                melekMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                melekMousePressed(evt);
            }
        });
        panellogin.add(melek, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 40, 30));

        picek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/invisible.jpg"))); // NOI18N
        picek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                picekMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                picekMousePressed(evt);
            }
        });
        panellogin.add(picek, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 40, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(252, 249, 137));
        jLabel4.setText("LOGIN");
        panellogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        passtxt.setBackground(new java.awt.Color(0, 0, 0));
        passtxt.setForeground(new java.awt.Color(252, 249, 137));
        passtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtxtActionPerformed(evt);
            }
        });
        panellogin.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 180, 30));

        forgotlabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        forgotlabel.setForeground(new java.awt.Color(252, 249, 137));
        forgotlabel.setText("klik disini");
        forgotlabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                forgotlabelMouseMoved(evt);
            }
        });
        forgotlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotlabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                forgotlabelMousePressed(evt);
            }
        });
        panellogin.add(forgotlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 60, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Lupa Password?");
        panellogin.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 100, 30));
        panellogin.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 40, 10));

        getContentPane().add(panellogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 450));

        setSize(new java.awt.Dimension(676, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setExtendedState(Login2.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void panelminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelminMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panelminMouseExited

    private void panelminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelminMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panelminMouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        panelx.setBackground(Color.WHITE);
        jLabel1.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        panelx.setBackground(Color.RED);
        jLabel1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        panelmin.setBackground(Color.WHITE);
        jLabel6.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        panelmin.setBackground(Color.BLACK);
         jLabel6.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void passtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtxtActionPerformed

    private void picekMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picekMousePressed
       
    }//GEN-LAST:event_picekMousePressed

    private void melekMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_melekMousePressed
        
    }//GEN-LAST:event_melekMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Fungsi untuk menampilkan halaman Registrasi Akun
        Register ter = new Register();
        ter.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //Fungsi untuk menampilkan halaman Dashboard jika memasukkan username dan password secara benar maka akan muncul notifikasi "Login Sukses" 
        try{
            con = (Connection) Koneksi.configDB();
            Statement s = con.createStatement();
            String query = "SELECT * FROM login WHERE username='" + inputtxt.getText() +"' and password='" + passtxt.getText() +"'";
            ResultSet rs = s.executeQuery(query);

            if(rs.next()){
                Dashboard2 bor = new Dashboard2();
                bor.setVisible(true);
                this.dispose();
                JOptionPane.showMessageDialog(null, "Login Sukses");

            }else{
                JOptionPane.showMessageDialog(null, "Username atau Password Tidak Sesuai");
            }
        }catch(SQLException ex){
            System.out.println("error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void forgotlabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlabelMousePressed
        //Fungsi untuk menampilkan halaman Lupa Password
        send_code sc = new send_code();
        this.setVisible(false);
        sc.setVisible(true);
    }//GEN-LAST:event_forgotlabelMousePressed

    private void forgotlabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlabelMouseMoved
        forgotlabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_forgotlabelMouseMoved

    private void inputtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputtxtActionPerformed

    }//GEN-LAST:event_inputtxtActionPerformed

    private void inputtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputtxtFocusLost

    }//GEN-LAST:event_inputtxtFocusLost

    private void inputtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputtxtFocusGained

    }//GEN-LAST:event_inputtxtFocusGained

    private void melekMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_melekMouseEntered
        picek.setVisible(true);
        melek.setVisible(false);
        passtxt.setEchoChar((char)0);
    }//GEN-LAST:event_melekMouseEntered

    private void picekMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picekMouseExited
        picek.setVisible(false);
        melek.setVisible(true);
        passtxt.setEchoChar('*');
    }//GEN-LAST:event_picekMouseExited

    private void forgotlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlabelMouseEntered
        line.setVisible(true);
    }//GEN-LAST:event_forgotlabelMouseEntered

    private void forgotlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlabelMouseExited
        line.setVisible(false);
    }//GEN-LAST:event_forgotlabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forgotlabel;
    private javax.swing.JTextField inputtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator line;
    private javax.swing.JLabel melek;
    private javax.swing.JPanel panellogin;
    private javax.swing.JPanel panelmin;
    private javax.swing.JPanel panelx;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JLabel picek;
    // End of variables declaration//GEN-END:variables
}
