/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class pemasok3 extends javax.swing.JFrame {

    public void tampilkan_data(){
    //Method yang berfungsi untuk menampilkan data dari tabel karyawan
   DefaultTableModel model = new DefaultTableModel();
   
   model.addColumn("No.");
   model.addColumn("NK");
   model.addColumn("nama_karyawan");
   model.addColumn("jenis_kelamin");
   model.addColumn("alamat_karyawan");
   model.addColumn("jabatan_karyawan");
   model.addColumn("gaji_karyawan");
   String cari = carikrwntxt.getText();
   try{
       int no = 1;
       String sql = "Select * From karyawan WHERE nama_karyawan LIKE'%"+cari+"%'";
       java.sql.Connection con = (Connection)Koneksi.configDB();
       java.sql.Statement stm = con.createStatement();
       java.sql.ResultSet res = stm.executeQuery(sql);
       
       while (res.next()){
           model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
           
           tabel_karyawan1.setModel(model);
           
       }
   }catch(SQLException e){
       System.out.println("ERROR :" +e.getMessage());
       
   }
}
     public void Kosongkan_form(){
        //method untuk  mengosongkan text dari kolom yang telah didefinisikan menjadi tidak bernilai (NULL) 
        idtxt1.setText(null);
        namatxt.setText(null);
        kelamintxt.setSelectedItem("Pilih Jenis Kelamin");
        alamattxt.setText(null);
        jabatantxt.setText(null);
        gajitxt.setSelectedItem("Pilih Gaji");
    }
     public void otomatis1(){
        //Method menampilkan id karyawan (NK) secara otomatis dari tabel karyawan
        try {
            Connection c = (Connection) Koneksi.configDB();
            Statement stm = c.createStatement();
            String sql = "SELECT * FROM karyawan ORDER BY NK DESC";
            ResultSet r = stm.executeQuery(sql);
            if (r.next()) {
                String id = r.getString("NK").substring(2);
                String TR = "" + (Integer.parseInt(id) + 1);
                String nol = "";

                if (TR.length() == 1) {
                    nol = "00";
                } else if (TR.length() == 2) {
                    nol = "0";
                } else if (TR.length() == 3) {
                    nol = "";
                }

                idtxt1.setText("KR" + nol + TR);
            } else {
                idtxt1.setText("KR008");
            }
            r.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    public pemasok3() {
        initComponents();
        
        tampilkan_data();
        Kosongkan_form();
        otomatis1();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        findbutton = new javax.swing.JButton();
        caribrgtxt = new javax.swing.JTextField();
        findbutton3 = new javax.swing.JButton();
        carikrwntxt = new javax.swing.JTextField();
        roundedPanel17 = new org.hq.RoundedPanel();
        roundedPanel16 = new org.hq.RoundedPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        refreshbtn = new javax.swing.JButton();
        idtxt1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        namatxt = new javax.swing.JTextField();
        jabatantxt = new javax.swing.JTextField();
        deletebutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_karyawan1 = new javax.swing.JTable();
        alamattxt = new javax.swing.JTextField();
        kelamintxt = new javax.swing.JComboBox<>();
        gajitxt = new javax.swing.JComboBox<>();
        jPanel21 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        roundedPanel13 = new org.hq.RoundedPanel();
        labelexit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panellogout = new org.hq.RoundedPanel();
        paneldash = new org.hq.RoundedPanel();
        labeltrans6 = new javax.swing.JLabel();
        panellap = new org.hq.RoundedPanel();
        labeltrans2 = new javax.swing.JLabel();
        panelkrwn = new org.hq.RoundedPanel();
        labeltrans3 = new javax.swing.JLabel();
        panelsup = new org.hq.RoundedPanel();
        labeltrans5 = new javax.swing.JLabel();
        panelrang = new org.hq.RoundedPanel();
        labeltrans4 = new javax.swing.JLabel();
        paneltrans = new org.hq.RoundedPanel();
        labeltrans1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(949, 748));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setText("   DATA KARYAWAN");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 40));

        findbutton.setBackground(new java.awt.Color(230, 230, 230));
        findbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/search_icon-icons.com_74128-picsay.png"))); // NOI18N
        findbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        findbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findbuttonMouseClicked(evt);
            }
        });
        findbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbuttonActionPerformed(evt);
            }
        });
        jPanel5.add(findbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 30, 30));

        caribrgtxt.setBackground(new java.awt.Color(0, 0, 0));
        caribrgtxt.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        caribrgtxt.setForeground(new java.awt.Color(255, 255, 255));
        caribrgtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        caribrgtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        caribrgtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caribrgtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                caribrgtxtFocusLost(evt);
            }
        });
        caribrgtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caribrgtxtMouseClicked(evt);
            }
        });
        caribrgtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caribrgtxtActionPerformed(evt);
            }
        });
        caribrgtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caribrgtxtKeyReleased(evt);
            }
        });
        jPanel5.add(caribrgtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 360, 30));

        findbutton3.setBackground(new java.awt.Color(230, 230, 230));
        findbutton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/search_icon-icons.com_74128-picsay.png"))); // NOI18N
        findbutton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        findbutton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findbutton3MouseClicked(evt);
            }
        });
        findbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbutton3ActionPerformed(evt);
            }
        });
        jPanel5.add(findbutton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, 30));

        carikrwntxt.setBackground(new java.awt.Color(0, 87, 118));
        carikrwntxt.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        carikrwntxt.setForeground(new java.awt.Color(252, 249, 137));
        carikrwntxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        carikrwntxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        carikrwntxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                carikrwntxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                carikrwntxtFocusLost(evt);
            }
        });
        carikrwntxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carikrwntxtMouseClicked(evt);
            }
        });
        carikrwntxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carikrwntxtActionPerformed(evt);
            }
        });
        carikrwntxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                carikrwntxtKeyReleased(evt);
            }
        });
        jPanel5.add(carikrwntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 180, 30));

        roundedPanel17.setBackground(new java.awt.Color(0, 87, 118));
        roundedPanel17.setRoundBottomLeft(15);
        roundedPanel17.setRoundBottomRight(15);
        roundedPanel17.setRoundTopLeft(15);
        roundedPanel17.setRoundTopRight(15);

        javax.swing.GroupLayout roundedPanel17Layout = new javax.swing.GroupLayout(roundedPanel17);
        roundedPanel17.setLayout(roundedPanel17Layout);
        roundedPanel17Layout.setHorizontalGroup(
            roundedPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        roundedPanel17Layout.setVerticalGroup(
            roundedPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel5.add(roundedPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 740, -1));

        roundedPanel16.setBackground(new java.awt.Color(252, 249, 137));
        roundedPanel16.setRoundBottomLeft(15);
        roundedPanel16.setRoundBottomRight(15);
        roundedPanel16.setRoundTopLeft(15);
        roundedPanel16.setRoundTopRight(15);

        javax.swing.GroupLayout roundedPanel16Layout = new javax.swing.GroupLayout(roundedPanel16);
        roundedPanel16.setLayout(roundedPanel16Layout);
        roundedPanel16Layout.setHorizontalGroup(
            roundedPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        roundedPanel16Layout.setVerticalGroup(
            roundedPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel5.add(roundedPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 740, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 1130, 80));

        jPanel9.setBackground(new java.awt.Color(0, 87, 118));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jenis Kelamin");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 20));

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Jabatan");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        jLabel31.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Nama Karyawan");
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 20));

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID Karyawan");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        refreshbtn.setBackground(new java.awt.Color(0, 0, 0));
        refreshbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refreshbtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshbtn.setText("BATAL");
        refreshbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });
        jPanel9.add(refreshbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 60, 30));

        idtxt1.setEditable(false);
        idtxt1.setBackground(new java.awt.Color(252, 249, 137));
        idtxt1.setForeground(new java.awt.Color(0, 87, 118));
        idtxt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        idtxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxt1ActionPerformed(evt);
            }
        });
        jPanel9.add(idtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, 20));

        jLabel32.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Gaji");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 60, 20));

        jLabel33.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Alamat");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 20));

        namatxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        namatxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        namatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namatxtActionPerformed(evt);
            }
        });
        jPanel9.add(namatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 180, 20));

        jabatantxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jabatantxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jabatantxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatantxtActionPerformed(evt);
            }
        });
        jPanel9.add(jabatantxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 180, 20));

        deletebutton.setBackground(new java.awt.Color(224, 25, 25));
        deletebutton.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        deletebutton.setForeground(new java.awt.Color(255, 255, 255));
        deletebutton.setText("Hapus");
        deletebutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deletebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebuttonMouseClicked(evt);
            }
        });
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel9.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 80, 30));

        updatebutton.setBackground(new java.awt.Color(230, 230, 230));
        updatebutton.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        updatebutton.setText("Edit");
        updatebutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updatebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebuttonMouseClicked(evt);
            }
        });
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel9.add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 80, 30));

        addbutton.setBackground(new java.awt.Color(224, 25, 25));
        addbutton.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        addbutton.setForeground(new java.awt.Color(255, 255, 255));
        addbutton.setText("Simpan");
        addbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        jPanel9.add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 80, 30));

        tabel_karyawan1.setBackground(new java.awt.Color(252, 249, 137));
        tabel_karyawan1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabel_karyawan1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tabel_karyawan1.setForeground(new java.awt.Color(0, 87, 118));
        tabel_karyawan1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIK", "Nama_karyawan", "Jenis_kelamin", "Alamat_karyawan", "Jabatan", "Gaji"
            }
        ));
        tabel_karyawan1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabel_karyawan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_karyawan1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_karyawan1);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 700, 290));

        alamattxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        alamattxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        alamattxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamattxtActionPerformed(evt);
            }
        });
        jPanel9.add(alamattxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 180, 20));

        kelamintxt.setBackground(new java.awt.Color(252, 249, 137));
        kelamintxt.setForeground(new java.awt.Color(0, 87, 118));
        kelamintxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kelamin", "Laki-laki", "Perempuan", "Lainnya" }));
        jPanel9.add(kelamintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, -1));

        gajitxt.setBackground(new java.awt.Color(252, 249, 137));
        gajitxt.setForeground(new java.awt.Color(0, 87, 118));
        gajitxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Gaji", "250000", "500000", "750000", "1000000", "1500000", "2000000" }));
        jPanel9.add(gajitxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 180, -1));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 720, 550));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 0, 740, 640));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setBackground(new java.awt.Color(0, 87, 118));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 87, 118));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("   MAIN  MENU");
        jPanel21.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/iconnew-picsay.png"))); // NOI18N
        jPanel21.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, -1));

        roundedPanel13.setBackground(new java.awt.Color(0, 0, 0));
        roundedPanel13.setRoundBottomLeft(15);
        roundedPanel13.setRoundBottomRight(15);
        roundedPanel13.setRoundTopLeft(15);
        roundedPanel13.setRoundTopRight(15);
        roundedPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelexit.setBackground(new java.awt.Color(255, 255, 255));
        labelexit.setForeground(new java.awt.Color(255, 255, 255));
        labelexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_komponen_figma/logoutnew().png"))); // NOI18N
        labelexit.setText("⟪⟪⟪");
        labelexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelexitMouseExited(evt);
            }
        });
        roundedPanel13.add(labelexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 30, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 87, 118));
        jLabel7.setText("DASHBOARD");
        roundedPanel13.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 180, 50));

        panellogout.setBackground(new java.awt.Color(0, 0, 0));
        panellogout.setRoundBottomLeft(15);
        panellogout.setRoundTopRight(15);

        javax.swing.GroupLayout panellogoutLayout = new javax.swing.GroupLayout(panellogout);
        panellogout.setLayout(panellogoutLayout);
        panellogoutLayout.setHorizontalGroup(
            panellogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panellogoutLayout.setVerticalGroup(
            panellogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        roundedPanel13.add(panellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 50, 50));

        paneldash.setBackground(new java.awt.Color(0, 0, 0));
        paneldash.setRoundBottomRight(15);
        paneldash.setRoundTopRight(15);

        labeltrans6.setBackground(new java.awt.Color(255, 255, 255));
        labeltrans6.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans6.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans6.setText("DASHBOARD");
        labeltrans6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneldashLayout = new javax.swing.GroupLayout(paneldash);
        paneldash.setLayout(paneldashLayout);
        paneldashLayout.setHorizontalGroup(
            paneldashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        paneldashLayout.setVerticalGroup(
            paneldashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldashLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(paneldash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, -1));

        panellap.setBackground(new java.awt.Color(0, 0, 0));
        panellap.setRoundBottomRight(15);
        panellap.setRoundTopRight(15);

        labeltrans2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans2.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans2.setText("LAPORAN");
        labeltrans2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panellapLayout = new javax.swing.GroupLayout(panellap);
        panellap.setLayout(panellapLayout);
        panellapLayout.setHorizontalGroup(
            panellapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panellapLayout.setVerticalGroup(
            panellapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panellapLayout.createSequentialGroup()
                .addComponent(labeltrans2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        roundedPanel13.add(panellap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 20));

        panelkrwn.setBackground(new java.awt.Color(255, 255, 255));
        panelkrwn.setRoundBottomRight(15);
        panelkrwn.setRoundTopRight(15);

        labeltrans3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans3.setText("DATA KARYAWAN");
        labeltrans3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelkrwnLayout = new javax.swing.GroupLayout(panelkrwn);
        panelkrwn.setLayout(panelkrwnLayout);
        panelkrwnLayout.setHorizontalGroup(
            panelkrwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkrwnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans3)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelkrwnLayout.setVerticalGroup(
            panelkrwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelkrwnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(panelkrwn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 20));

        panelsup.setBackground(new java.awt.Color(0, 0, 0));
        panelsup.setRoundBottomRight(15);
        panelsup.setRoundTopRight(15);

        labeltrans5.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans5.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans5.setText("DATA SUPPLIER");
        labeltrans5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelsupLayout = new javax.swing.GroupLayout(panelsup);
        panelsup.setLayout(panelsupLayout);
        panelsupLayout.setHorizontalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans5)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelsupLayout.setVerticalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(panelsup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 20));

        panelrang.setBackground(new java.awt.Color(0, 0, 0));
        panelrang.setRoundBottomRight(15);
        panelrang.setRoundTopRight(15);

        labeltrans4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans4.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans4.setText("DATA BARANG");
        labeltrans4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelrangLayout = new javax.swing.GroupLayout(panelrang);
        panelrang.setLayout(panelrangLayout);
        panelrangLayout.setHorizontalGroup(
            panelrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans4)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        panelrangLayout.setVerticalGroup(
            panelrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelrangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(panelrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 20));

        paneltrans.setBackground(new java.awt.Color(0, 0, 0));
        paneltrans.setRoundBottomRight(15);
        paneltrans.setRoundTopRight(15);

        labeltrans1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        labeltrans1.setForeground(new java.awt.Color(255, 255, 255));
        labeltrans1.setText("TRANSAKSI");
        labeltrans1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneltransLayout = new javax.swing.GroupLayout(paneltrans);
        paneltrans.setLayout(paneltransLayout);
        paneltransLayout.setHorizontalGroup(
            paneltransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltransLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltrans1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        paneltransLayout.setVerticalGroup(
            paneltransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltransLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltrans1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundedPanel13.add(paneltrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 160, -1));

        jPanel21.add(roundedPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, 480));

        getContentPane().add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 640));

        setSize(new java.awt.Dimension(929, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void findbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findbuttonMouseClicked
        tampilkan_data();
    }//GEN-LAST:event_findbuttonMouseClicked

    private void findbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbuttonActionPerformed

    }//GEN-LAST:event_findbuttonActionPerformed

    private void caribrgtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caribrgtxtFocusGained

    }//GEN-LAST:event_caribrgtxtFocusGained

    private void caribrgtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caribrgtxtFocusLost

    }//GEN-LAST:event_caribrgtxtFocusLost

    private void caribrgtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caribrgtxtMouseClicked

    }//GEN-LAST:event_caribrgtxtMouseClicked

    private void caribrgtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caribrgtxtActionPerformed

    }//GEN-LAST:event_caribrgtxtActionPerformed

    private void caribrgtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caribrgtxtKeyReleased

    }//GEN-LAST:event_caribrgtxtKeyReleased

    private void findbutton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findbutton3MouseClicked
        tampilkan_data();
    }//GEN-LAST:event_findbutton3MouseClicked

    private void findbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbutton3ActionPerformed

    }//GEN-LAST:event_findbutton3ActionPerformed

    private void carikrwntxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_carikrwntxtFocusGained

    }//GEN-LAST:event_carikrwntxtFocusGained

    private void carikrwntxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_carikrwntxtFocusLost

    }//GEN-LAST:event_carikrwntxtFocusLost

    private void carikrwntxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carikrwntxtMouseClicked

    }//GEN-LAST:event_carikrwntxtMouseClicked

    private void carikrwntxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carikrwntxtActionPerformed
 tampilkan_data();
 carikrwntxt.setText(null);
 
        
    
    }//GEN-LAST:event_carikrwntxtActionPerformed

    private void carikrwntxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carikrwntxtKeyReleased
tampilkan_data();
    }//GEN-LAST:event_carikrwntxtKeyReleased

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        Kosongkan_form();
        otomatis1();
    }//GEN-LAST:event_refreshbtnActionPerformed

    private void idtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxt1ActionPerformed

    private void namatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namatxtActionPerformed

    private void jabatantxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatantxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jabatantxtActionPerformed

    private void deletebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebuttonMouseClicked
        //Aksi yang digunakan untuk menghapus data dari tabel karyawan berdasarkan kolom NK
        int opt =  JOptionPane.showConfirmDialog(this, "Apakah Yakin Ingin Menghapus Data Ini?", "Hapus", JOptionPane.YES_NO_OPTION);
        if(opt == 0){
        try{
            String sql = "DELETE FROM karyawan WHERE NK ='"+idtxt1.getText()+"'";
            java.sql.Connection con = (Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");

        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
        tampilkan_data();
        Kosongkan_form();
        otomatis1();
    }//GEN-LAST:event_deletebuttonMouseClicked

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed

    }//GEN-LAST:event_deletebuttonActionPerformed

    private void updatebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebuttonMouseClicked
        //Aksi yang digunakan untuk mengupdate data dari tabel karyawan
        try{
            String sql = "INSERT karyawan SET NK='"+idtxt1.getText()+"' ,nama_karyawan='"+namatxt.getText()+"' ,jenis_kelamin='"+kelamintxt.getSelectedItem()+"' ,alamat_karyawan='"+alamattxt.getText()+"' ,jabatan='"+jabatantxt.getText()+"' ,gaji='"+gajitxt.getSelectedItem()+"' On Duplicate Key Update NK='"+idtxt1.getText()+"' ,nama_karyawan='"+namatxt.getText()+"' ,jenis_kelamin='"+kelamintxt.getSelectedItem()+"' ,alamat_karyawan='"+alamattxt.getText()+"' ,jabatan='"+jabatantxt.getText()+"' ,gaji='"+gajitxt.getSelectedItem()+"'";
            java.sql.Connection con = (Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
        tampilkan_data();
        Kosongkan_form();
        otomatis1();
    }//GEN-LAST:event_updatebuttonMouseClicked

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed

    }//GEN-LAST:event_updatebuttonActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        //Fungsi yang digunakan untuk menambah data ke dalam tabel karyawan
        try{
            String sql = "INSERT INTO karyawan VALUES ('"+idtxt1.getText()+"','"+namatxt.getText()+"','"+kelamintxt.getSelectedItem()+"','"+alamattxt.getText()+"','"+jabatantxt.getText()+"','"+gajitxt.getSelectedItem()+"')";
            java.sql.Connection con = (Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Simpan Data Berhasil");

        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, "Simpan Data Gagal");
        }
        tampilkan_data();
        Kosongkan_form();
        otomatis1();
    }//GEN-LAST:event_addbuttonActionPerformed

    private void tabel_karyawan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_karyawan1MouseClicked
        //Aksi yang digunakan untuk menampilkan data dari tabel_karyawan ke kolom text yang telah didefinisikan ketika salah satu baris diklik
        int baris = tabel_karyawan1.rowAtPoint(evt.getPoint());
        String id = tabel_karyawan1.getValueAt(baris, 1).toString();
        idtxt1.setText(id);
        String nama = tabel_karyawan1.getValueAt(baris, 2).toString();
        namatxt.setText(nama);
        String kelamin = tabel_karyawan1.getValueAt(baris, 3).toString();
        kelamintxt.setSelectedItem(kelamin);
        String alamat = tabel_karyawan1.getValueAt(baris, 4).toString();
        alamattxt.setText(alamat);
        String jabatan = tabel_karyawan1.getValueAt(baris, 5).toString();
        jabatantxt.setText(jabatan);
        String gaji = tabel_karyawan1.getValueAt(baris, 6).toString();
        gajitxt.setSelectedItem(gaji);
    }//GEN-LAST:event_tabel_karyawan1MouseClicked

    private void alamattxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamattxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamattxtActionPerformed

    private void labelexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexitMouseClicked
        Login2 login = new Login2();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelexitMouseClicked

    private void labelexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexitMouseEntered
        // TODO add your handling code here:
        labelexit.setForeground(Color.RED);
        panellogout.setBackground(Color.RED);
    }//GEN-LAST:event_labelexitMouseEntered

    private void labelexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexitMouseExited
        labelexit.setForeground(Color.WHITE);
        panellogout.setBackground(Color.BLACK);
    }//GEN-LAST:event_labelexitMouseExited

    private void labeltrans6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans6MouseClicked
        try {
            Dashboard2 d = new Dashboard2();
            d.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(transaksi2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labeltrans6MouseClicked

    private void labeltrans6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans6MouseEntered
        labeltrans6.setForeground(Color.BLACK);
        paneldash.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans6MouseEntered

    private void labeltrans6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans6MouseExited
        labeltrans6.setForeground(Color.WHITE);
        paneldash.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans6MouseExited

    private void labeltrans2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans2MouseClicked
        // TODO add your handling code here:
        Laporan ran = new Laporan();
        ran.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labeltrans2MouseClicked

    private void labeltrans2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans2MouseEntered
        // TODO add your handling code here:
        labeltrans2.setForeground(Color.BLACK);
        panellap.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans2MouseEntered

    private void labeltrans2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans2MouseExited
        // TODO add your handling code here:
        labeltrans2.setForeground(Color.WHITE);
        panellap.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans2MouseExited

    private void labeltrans3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans3MouseClicked

    }//GEN-LAST:event_labeltrans3MouseClicked

    private void labeltrans3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans3MouseEntered

    }//GEN-LAST:event_labeltrans3MouseEntered

    private void labeltrans3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans3MouseExited

    }//GEN-LAST:event_labeltrans3MouseExited

    private void labeltrans5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans5MouseClicked
        // TODO add your handling code here:
        supplier2 s = new supplier2();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labeltrans5MouseClicked

    private void labeltrans5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans5MouseEntered
        // TODO add your handling code here:
        labeltrans5.setForeground(Color.BLACK);
        panelsup.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans5MouseEntered

    private void labeltrans5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans5MouseExited
        // TODO add your handling code here:
        labeltrans5.setForeground(Color.WHITE);
        panelsup.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans5MouseExited

    private void labeltrans4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans4MouseClicked

        try {
            // TODO add your handling code here:
            barang2 rg = new barang2();
            rg.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_labeltrans4MouseClicked

    private void labeltrans4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans4MouseEntered
        // TODO add your handling code here:
        labeltrans4.setForeground(Color.BLACK);
        panelrang.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans4MouseEntered

    private void labeltrans4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans4MouseExited
        // TODO add your handling code here:
        labeltrans4.setForeground(Color.WHITE);
        panelrang.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans4MouseExited

    private void labeltrans1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans1MouseClicked
        transaksi2 t = new transaksi2();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labeltrans1MouseClicked

    private void labeltrans1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans1MouseEntered
        labeltrans1.setForeground(Color.BLACK);
        paneltrans.setBackground(Color.WHITE);
    }//GEN-LAST:event_labeltrans1MouseEntered

    private void labeltrans1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans1MouseExited
        labeltrans1.setForeground(Color.WHITE);
        paneltrans.setBackground(Color.BLACK);
    }//GEN-LAST:event_labeltrans1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemasok3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemasok3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemasok3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemasok3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemasok3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JTextField alamattxt;
    private javax.swing.JTextField caribrgtxt;
    private javax.swing.JTextField carikrwntxt;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton findbutton;
    private javax.swing.JButton findbutton3;
    private javax.swing.JComboBox<String> gajitxt;
    private javax.swing.JTextField idtxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jabatantxt;
    private javax.swing.JComboBox<String> kelamintxt;
    private javax.swing.JLabel labelexit;
    private javax.swing.JLabel labeltrans1;
    private javax.swing.JLabel labeltrans2;
    private javax.swing.JLabel labeltrans3;
    private javax.swing.JLabel labeltrans4;
    private javax.swing.JLabel labeltrans5;
    private javax.swing.JLabel labeltrans6;
    private javax.swing.JTextField namatxt;
    private org.hq.RoundedPanel paneldash;
    private org.hq.RoundedPanel panelkrwn;
    private org.hq.RoundedPanel panellap;
    private org.hq.RoundedPanel panellogout;
    private org.hq.RoundedPanel panelrang;
    private org.hq.RoundedPanel panelsup;
    private org.hq.RoundedPanel paneltrans;
    private javax.swing.JButton refreshbtn;
    private org.hq.RoundedPanel roundedPanel13;
    private org.hq.RoundedPanel roundedPanel16;
    private org.hq.RoundedPanel roundedPanel17;
    private javax.swing.JTable tabel_karyawan1;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables

    private void setText(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
